# .air.toml
# Config file for air: https://github.com/cosmtrek/air

# The root directory of your project
root = "."
tmp_dir = "tmp"

[build]
# Command to build your application
cmd = "go build -o ./tmp/main ./cmd/server/main.go"
# The binary to run
bin = "./tmp/main"
# Watch these file extensions
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these directories
exclude_dir = ["tmp", "vendor", "files", "migrations"]
# Log file for air's output
log = "air.log"
# Delay in milliseconds before restarting
delay = 1000 # 1s

[log]
# Show log time
time = true

[color]
# Customize colors
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true