version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: go-blog-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d blog"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: go-blog-app
    restart: on-failure
    ports:
      - "8080:8080"
    # Mount the source code into the container
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    # Override the Dockerfile's CMD to install and run air for development
    command: sh -c "go install github.com/cosmtrek/air@latest && air"
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=postgres://user:password@db:5432/blog?sslmode=disable
      - STORAGE_TYPE=local # Change to 's3' for production and add S3 env vars

volumes:
  postgres_data: