name: Go Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: blog
        ports:
          - 5432:5432
        # Health check to wait until postgres is ready
        options: >-
          --health-cmd "pg_isready -U user -d blog"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Run database migrations
        run: migrate -path migrations -database "postgres://user:password@localhost:5432/blog?sslmode=disable" up

      - name: Run tests
        run: go test -v ./...
        env:
          # The tests will need this environment variable to connect to the database service
          DATABASE_URL: "postgres://user:password@localhost:5432/blog?sslmode=disable"
          # Add other environment variables your tests might need
          SERVER_PORT: 8080
          STORAGE_TYPE: local